[server]
# Ultra-conservative file upload settings for maximum Render compatibility
maxUploadSize = 3
maxMessageSize = 3
enableWebsocketCompression = false
enableCORS = false
enableXsrfProtection = false

# Enhanced timeout and connection settings
disconnectedSessionTTL = 30
sessionStateMaxEntries = 500
sessionStateMaxBytes = 50

# Network timeout optimizations
connectionTimeout = 30
keepAliveTimeout = 30
requestTimeout = 30

# Memory and performance optimizations
enableArrowTruncation = true

# Cloud platform settings
port = 8501
address = "0.0.0.0"
headless = true

# Browser settings
gatherUsageStats = false

[browser]
gatherUsageStats = false
serverAddress = "0.0.0.0"
serverPort = 8501

[theme]
primaryColor = "#155a5a"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f0f2f6"
textColor = "#262730"

[global]
# Development settings
developmentMode = false
logLevel = "error"

# Ultra-conservative memory settings
maxCachedMessageAge = 0
dataFrameSerialization = "legacy"
showErrorDetails = false

# Network timeout settings
[client]
caching = false
displayEnabled = true
toolbarMode = "minimal" 
